format = '$all'

[directory]
style = "blue"

[directory.substitutions]
"Desktop" = "Desktop ğŸ’» "
"Documents" = "Documents ğŸ“‘ "
"Downloads" = "Downloads ğŸ“¥ "
"Music" = " Music ó°š "
"Pictures" = "Pictures ğŸ“¸ "
"Developer" = "ó°²‹ "

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

<<<<<<< HEAD
[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
=======
[hostname]
ssh_symbol = "î¬ "

[package]
symbol = "ó°— "
>>>>>>> 5193d0d8bea5b6fc3d500cf559e06e6f629b221b

[git_branch]
format = '\[[$symbol$branch]($style)\]'
style = "bright-black"
symbol = "ï˜ "

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[sudo]
format = '\[[as $symbol]($style)\]'

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"


